//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQuery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Courses_tbl()
        {
            this.Specializations_tbl = new HashSet<Specializations_tbl>();
        }
    
        public int course_id { get; set; }
        public Nullable<int> stream_id { get; set; }
        public string course_name { get; set; }
    
        public virtual Streams_tbl Streams_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specializations_tbl> Specializations_tbl { get; set; }
    }
}
