//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQuery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JQueryEntities : DbContext
    {
        public JQueryEntities()
            : base("name=JQueryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_JQ> Category_JQ { get; set; }
        public virtual DbSet<Courses_tbl> Courses_tbl { get; set; }
        public virtual DbSet<Specializations_tbl> Specializations_tbl { get; set; }
        public virtual DbSet<Streams_tbl> Streams_tbl { get; set; }
    }
}
