//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JQuery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specializations_tbl
    {
        public int specialization_id { get; set; }
        public Nullable<int> course_id { get; set; }
        public string specialization_name { get; set; }
    
        public virtual Courses_tbl Courses_tbl { get; set; }
    }
}
